// Business Information
export const BUSINESS = {
  name: 'Best Remodeling & Refinishing',
  tagline: 'Seattle Kitchen & Bath Remodeling Experts',
  phone: '(206) 786-9915',
  phoneLink: 'tel:+12067869915',
  smsLink: 'sms:+12067869915',
  email: 'office@best-refinishing.com',
  website: 'https://www.best-refinishing.com',
  hours: 'Open 24/7',
  responseTime: 'Instantly',
  warranty: '5 Years',
  experience: '15+',
  projectsCompleted: '500+',
  rating: '4.98',
  reviewCount: '87',
} as const;

// Services
export const SERVICES = [
  {
    id: 'bathtub',
    title: 'Bathtub Refinishing',
    shortTitle: 'Bathtub',
    subtitle: 'Most Popular',
    description: 'Cracked, stained, or outdated tub? We restore it to factory-fresh condition in just 4-6 hours. Looks brand new, costs 80% less than replacement.',
    longDescription: 'Professional bathtub refinishing restores your worn, damaged, or outdated bathtub to like-new condition. Our expert technicians use commercial-grade coatings and professional HVLP spray equipment to deliver a flawless, glass-like finish that lasts for years. Tub with surrounding walls available from $900.',
    features: ['Same-day service', 'Any color available', '5-year warranty', 'Porcelain, Cast Iron, Fiberglass'],
    price: 'From $700',
    savings: 'Save $4,000+',
    popular: true,
    image: '/images/optimized/baztub-after.webp',
    imagePosition: 'center 70%',
    imageScale: 1,
    beforeImage: '/images/optimized/bathtub-3-before.webp',
    href: '/services/bathtub-refinishing',
  },
  {
    id: 'shower',
    title: 'Shower Refinishing',
    shortTitle: 'Shower',
    subtitle: 'Full Restoration',
    description: 'Eliminate mold, mildew, and years of buildup. We restore your entire shower enclosure — walls, floor, and fixtures — to pristine condition.',
    longDescription: 'Complete shower refinishing eliminates years of mold, mildew, and staining. We restore fiberglass, acrylic, and tile shower enclosures to pristine condition with our professional reglazing process.',
    features: ['Mold-resistant finish', 'Anti-slip options', 'Ready in 24hrs', 'All materials'],
    price: 'From $900',
    savings: 'Save $5,000+',
    popular: false,
    image: '/images/optimized/shower-bg.webp',
    imagePosition: 'center',
    imageScale: 1,
    href: '/services/shower-refinishing',
  },
  {
    id: 'tile',
    title: 'Tile & Grout Refinishing',
    shortTitle: 'Tile',
    subtitle: 'Complete Refresh',
    description: 'Transform dated pink, green, or stained tiles without demolition. We refinish tile AND grout for a completely new look in one day.',
    longDescription: 'Tile and grout refinishing transforms your dated or damaged ceramic and porcelain tiles without the mess and cost of replacement. We refinish both tile surfaces and grout lines for a complete refresh.',
    features: ['No messy demolition', 'Grout included', 'Modern colors', 'Ceramic & Porcelain'],
    price: 'From $400',
    savings: 'Save $6,000+',
    popular: false,
    image: '/images/optimized/tiles-bg.webp',
    imagePosition: 'center',
    imageScale: 1,
    href: '/services/tile-refinishing',
  },
  {
    id: 'sink',
    title: 'Sink Refinishing',
    shortTitle: 'Sink',
    subtitle: 'Kitchen & Bath',
    description: 'Chips, rust stains, or worn finish? We refinish porcelain, cast iron, and fiberglass sinks to look showroom-new. Done in 2-3 hours.',
    longDescription: 'Sink refinishing restores your kitchen or bathroom sink to showroom condition. We repair chips, eliminate rust stains, and apply a durable new finish to porcelain, cast iron, and cultured marble sinks.',
    features: ['Stain-resistant', 'Chip repair included', 'Quick turnaround', 'All sink types'],
    price: 'From $450',
    savings: 'Save $800+',
    popular: false,
    image: '/images/optimized/sink-after-1.webp',
    imagePosition: 'center',
    imageScale: 1,
    href: '/services/sink-refinishing',
  },
  {
    id: 'countertop',
    title: 'Countertop Refinishing',
    shortTitle: 'Countertop',
    subtitle: 'Modern Update',
    description: 'Update laminate, tile, or cultured marble countertops to a sleek, modern finish. Granite and marble looks available at a fraction of the cost.',
    longDescription: 'Countertop refinishing updates your kitchen or bathroom countertops without costly replacement. Transform laminate, tile, or cultured marble surfaces to a modern finish with granite or marble-look options.',
    features: ['Stone-look finishes', 'Heat resistant', 'Seamless result', 'Multiple styles'],
    price: 'From $600',
    savings: 'Save $3,000+',
    popular: false,
    image: '/images/optimized/axmnd_httpss.mj.runGBOjqX76P3k______--ar_7758_--profile_klaqj_95c0c2cf-9d33-480a-98c4-a1e1b24e1c38_3.webp',
    imagePosition: 'center',
    imageScale: 1,
    href: '/services/countertop-refinishing',
  },
  {
    id: 'repair',
    title: 'Chip & Crack Repair',
    shortTitle: 'Repair',
    subtitle: 'Quick Fix',
    description: 'Small damage? No problem. We repair chips, cracks, and scratches on any surface — often same day. Invisible repairs guaranteed.',
    longDescription: 'Professional chip and crack repair fixes damage on bathtubs, sinks, tiles, and countertops. Our invisible repair technique restores surfaces without the need for complete refinishing.',
    features: ['Same-day service', 'Invisible repairs', 'All surfaces', 'Affordable'],
    price: 'From $350',
    savings: 'Quick & affordable',
    popular: false,
    image: '/images/optimized/local-bg1.webp',
    imagePosition: 'center',
    imageScale: 1,
    href: '/services/repair',
  },
] as const;

// Remodeling Services (PRIMARY business)
export const REMODELING_SERVICES = [
  {
    id: 'bathroom-remodeling',
    title: 'Bathroom Remodeling',
    shortTitle: 'Bathroom',
    subtitle: 'Full Remodel',
    description: 'Complete bathroom transformations — from design to installation. New tile, vanity, shower, fixtures, and more. Turn your outdated bathroom into a modern retreat.',
    longDescription: 'Our full-service bathroom remodeling covers everything: demolition, plumbing, electrical, tile installation, vanity and countertop installation, shower/tub replacement, fixtures, and finishing. We handle permits and coordinate all trades for a stress-free renovation experience.',
    features: ['Full design & build', 'Licensed & permitted', 'All trades in-house', 'Porcelain, Marble, Quartz'],
    price: 'From $7,900',
    savings: 'Complete Transform',
    popular: true,
    image: '/images/remodeling/bathroom-hero.jpeg',
    imagePosition: 'center',
    imageScale: 1,
    href: '/services/bathroom-remodeling',
  },
  {
    id: 'kitchen-remodeling',
    title: 'Kitchen Remodeling',
    shortTitle: 'Kitchen',
    subtitle: 'Full Remodel',
    description: 'Transform your kitchen with new cabinets, countertops, tile, fixtures, and layout updates. From minor refreshes to complete gut renovations.',
    longDescription: 'Our kitchen remodeling services include cabinet installation, countertop fabrication and installation, tile backsplash, flooring, plumbing, electrical upgrades, and custom storage solutions. We work with you on design and material selection to create your dream kitchen.',
    features: ['Custom cabinetry options', 'Countertop installation', 'Backsplash & flooring', 'Plumbing & electrical'],
    price: 'From $25,000',
    savings: 'Dream Kitchen',
    popular: true,
    image: '/images/remodeling/kitchen-hero.png',
    imagePosition: 'center',
    imageScale: 1,
    href: '/services/kitchen-remodeling',
  },
  {
    id: 'tile-installation',
    title: 'Tile Installation',
    shortTitle: 'Tile',
    subtitle: 'Professional Install',
    description: 'Expert tile installation for floors, walls, showers, and backsplashes. Ceramic, porcelain, marble, and natural stone — precision installation that lasts.',
    longDescription: 'Professional tile installation for kitchens, bathrooms, and living areas. We work with ceramic, porcelain, marble, travertine, and all natural stone. Our services include floor tile, wall tile, shower tile, backsplash installation, and custom mosaic work.',
    features: ['All tile types', 'Floor & wall installation', 'Shower & backsplash', 'Custom patterns'],
    price: 'From $7/sq ft',
    savings: 'Expert Install',
    popular: false,
    image: '/images/optimized/tiles-bg.webp',
    imagePosition: 'center',
    imageScale: 1,
    href: '/services/tile-installation',
  },
  {
    id: 'countertop-installation',
    title: 'Countertop Installation',
    shortTitle: 'Countertop',
    subtitle: 'Premium Surfaces',
    description: 'Professional countertop installation — granite, quartz, marble, and solid surface. Precision measurement, fabrication, and seamless installation.',
    longDescription: 'We install kitchen and bathroom countertops in granite, quartz, marble, quartzite, and solid surface materials. Our service includes template measurement, fabrication coordination, old countertop removal, and professional installation with undermount sink cutouts.',
    features: ['Granite & quartz', 'Marble & quartzite', 'Precision templating', 'Sink cutouts included'],
    price: 'From $2,000',
    savings: 'Premium Quality',
    popular: false,
    image: '/images/optimized/axmnd_httpss.mj.runGBOjqX76P3k______--ar_7758_--profile_klaqj_95c0c2cf-9d33-480a-98c4-a1e1b24e1c38_3.webp',
    imagePosition: 'center',
    imageScale: 1,
    href: '/services/countertop-installation',
  },
  {
    id: 'shower-installation',
    title: 'Shower Installation',
    shortTitle: 'Shower',
    subtitle: 'Custom Showers',
    description: 'Custom shower installation and replacement. Walk-in showers, tub-to-shower conversions, glass enclosures, and complete shower remodels.',
    longDescription: 'From basic shower replacements to custom walk-in showers, we handle every aspect: demolition, waterproofing, tile installation, glass door fitting, fixtures, and finishing. We also do tub-to-shower conversions and curbless shower installations for accessibility.',
    features: ['Walk-in showers', 'Tub-to-shower conversion', 'Glass enclosures', 'Waterproof systems'],
    price: 'From $2,000',
    savings: 'Custom Design',
    popular: false,
    image: '/images/remodeling/shower-hero.png',
    imagePosition: 'center',
    imageScale: 1,
    href: '/services/shower-installation',
  },
  {
    id: 'bathtub-installation',
    title: 'Bathtub Installation',
    shortTitle: 'Bathtub',
    subtitle: 'New Tub Install',
    description: 'Professional bathtub installation and replacement. Freestanding, alcove, drop-in, and soaking tubs. Includes plumbing, surround, and finishing.',
    longDescription: 'Complete bathtub installation services including removal of old tub, plumbing modifications, new tub installation, surround installation, waterproofing, and finishing. We install freestanding, alcove, drop-in, corner, and soaking tubs from all major manufacturers.',
    features: ['All tub styles', 'Plumbing included', 'Surround installation', 'Waterproofing'],
    price: 'From $2,400',
    savings: 'Fresh Start',
    popular: false,
    image: '/images/remodeling/bathtub-hero.jpg',
    imagePosition: 'center 70%',
    imageScale: 1,
    href: '/services/bathtub-installation',
  },
] as const;

// Keep original refinishing services accessible
export const REFINISHING_SERVICES = SERVICES;

// All services combined — remodeling first for UI components
export const ALL_SERVICES = [...REMODELING_SERVICES, ...REFINISHING_SERVICES] as const;

// Locations for Local SEO
export const LOCATIONS = [
  { id: 'seattle', name: 'Seattle', href: '/locations/seattle', primary: true },
  { id: 'bellevue', name: 'Bellevue', href: '/locations/bellevue', primary: true },
  { id: 'redmond', name: 'Redmond', href: '/locations/redmond', primary: true },
  { id: 'kirkland', name: 'Kirkland', href: '/locations/kirkland', primary: true },
  { id: 'bothell', name: 'Bothell', href: '/locations/bothell', primary: true },
  { id: 'renton', name: 'Renton', href: '/locations/renton', primary: true },
  { id: 'kent', name: 'Kent', href: '/locations/kent', primary: true },
  { id: 'federal-way', name: 'Federal Way', href: '/locations/federal-way', primary: true },
  { id: 'tacoma', name: 'Tacoma', href: '/locations/tacoma', primary: true },
  { id: 'lynnwood', name: 'Lynnwood', href: '/locations/lynnwood', primary: true },
  { id: 'sammamish', name: 'Sammamish', href: '/locations/sammamish', primary: true },
  { id: 'issaquah', name: 'Issaquah', href: '/locations/issaquah', primary: true },
] as const;

// Additional nearby areas for broader SEO coverage
export const ADDITIONAL_LOCATIONS = [
  { id: 'shoreline', name: 'Shoreline', href: '/locations/shoreline', primary: false },
  { id: 'burien', name: 'Burien', href: '/locations/burien', primary: false },
  { id: 'tukwila', name: 'Tukwila', href: '/locations/tukwila', primary: false },
  { id: 'seatac', name: 'SeaTac', href: '/locations/seatac', primary: false },
  { id: 'mercer-island', name: 'Mercer Island', href: '/locations/mercer-island', primary: false },
  { id: 'woodinville', name: 'Woodinville', href: '/locations/woodinville', primary: false },
  { id: 'kenmore', name: 'Kenmore', href: '/locations/kenmore', primary: false },
  { id: 'lake-forest-park', name: 'Lake Forest Park', href: '/locations/lake-forest-park', primary: false },
  { id: 'mountlake-terrace', name: 'Mountlake Terrace', href: '/locations/mountlake-terrace', primary: false },
  { id: 'edmonds', name: 'Edmonds', href: '/locations/edmonds', primary: false },
  { id: 'mukilteo', name: 'Mukilteo', href: '/locations/mukilteo', primary: false },
  { id: 'everett', name: 'Everett', href: '/locations/everett', primary: false },
  { id: 'auburn', name: 'Auburn', href: '/locations/auburn', primary: false },
  { id: 'covington', name: 'Covington', href: '/locations/covington', primary: false },
  { id: 'maple-valley', name: 'Maple Valley', href: '/locations/maple-valley', primary: false },
  { id: 'newcastle', name: 'Newcastle', href: '/locations/newcastle', primary: false },
  { id: 'clyde-hill', name: 'Clyde Hill', href: '/locations/clyde-hill', primary: false },
  { id: 'medina', name: 'Medina', href: '/locations/medina', primary: false },
  { id: 'hunts-point', name: 'Hunts Point', href: '/locations/hunts-point', primary: false },
  { id: 'yarrow-point', name: 'Yarrow Point', href: '/locations/yarrow-point', primary: false },
  { id: 'des-moines', name: 'Des Moines', href: '/locations/des-moines', primary: false },
  { id: 'normandy-park', name: 'Normandy Park', href: '/locations/normandy-park', primary: false },
  { id: 'white-center', name: 'White Center', href: '/locations/white-center', primary: false },
  { id: 'lake-city', name: 'Lake City', href: '/locations/lake-city', primary: false },
  { id: 'ballard', name: 'Ballard', href: '/locations/ballard', primary: false },
  { id: 'west-seattle', name: 'West Seattle', href: '/locations/west-seattle', primary: false },
  { id: 'capitol-hill', name: 'Capitol Hill', href: '/locations/capitol-hill', primary: false },
  { id: 'queen-anne', name: 'Queen Anne', href: '/locations/queen-anne', primary: false },
  { id: 'fremont', name: 'Fremont', href: '/locations/fremont', primary: false },
  { id: 'greenwood', name: 'Greenwood', href: '/locations/greenwood', primary: false },
  { id: 'university-district', name: 'University District', href: '/locations/university-district', primary: false },
  { id: 'columbia-city', name: 'Columbia City', href: '/locations/columbia-city', primary: false },
  { id: 'beacon-hill', name: 'Beacon Hill', href: '/locations/beacon-hill', primary: false },
  { id: 'georgetown', name: 'Georgetown', href: '/locations/georgetown', primary: false },
  { id: 'rainier-valley', name: 'Rainier Valley', href: '/locations/rainier-valley', primary: false },
  { id: 'northgate', name: 'Northgate', href: '/locations/northgate', primary: false },
  { id: 'magnolia', name: 'Magnolia', href: '/locations/magnolia', primary: false },
  { id: 'alki', name: 'Alki', href: '/locations/alki', primary: false },
] as const;

// All locations combined for SEO
export const ALL_LOCATIONS = [...LOCATIONS, ...ADDITIONAL_LOCATIONS] as const;

// 6-Step Process
export const PROCESS_STEPS = [
  {
    number: 1,
    title: 'Free Inspection & Quote',
    description: 'Our technician assesses your surface condition and provides an accurate, no-obligation quote on the spot.',
    color: '#0b66b3',
  },
  {
    number: 2,
    title: 'Surface Preparation',
    description: 'We thoroughly clean and prepare the surface, repairing any chips, cracks, or damage before refinishing.',
    color: '#f59e0b',
  },
  {
    number: 3,
    title: 'Professional Masking',
    description: 'We carefully mask and protect surrounding areas to ensure a clean, precise refinishing job.',
    color: '#10b981',
  },
  {
    number: 4,
    title: 'Primer & Topcoat Application',
    description: 'We apply 3 coats of commercial-grade bonding primer followed by 3 layers of premium topcoat using professional HVLP equipment for maximum durability.',
    color: '#8b5cf6',
  },
  {
    number: 5,
    title: 'Quality Inspection',
    description: 'Our technician performs a thorough quality check to ensure a flawless, glass-like finish.',
    color: '#ec4899',
  },
  {
    number: 6,
    title: 'Ready in 24 Hours',
    description: 'Your professionally refinished surface is ready to use in just 24 hours. Full cure in 7 days for maximum durability.',
    color: '#06b6d4',
  },
] as const;

export const REMODELING_PROCESS_STEPS = [
  {
    number: 1,
    title: 'Free Consultation & Estimate',
    description: 'We visit your home, discuss your vision, take measurements, and provide a detailed written estimate with material options.',
    color: '#0b66b3',
  },
  {
    number: 2,
    title: 'Design & Material Selection',
    description: 'Choose your materials, colors, and finishes. We help you select the best options for your budget and style preferences.',
    color: '#f59e0b',
  },
  {
    number: 3,
    title: 'Demolition & Preparation',
    description: 'We carefully remove old fixtures, protect your home, and prepare the space for new installations. Permits handled as needed.',
    color: '#10b981',
  },
  {
    number: 4,
    title: 'Plumbing & Electrical',
    description: 'Licensed professionals handle all plumbing and electrical work, including any layout changes or upgrades required.',
    color: '#8b5cf6',
  },
  {
    number: 5,
    title: 'Installation & Finishing',
    description: 'Expert installation of tile, countertops, fixtures, cabinetry, and all finishing details. Quality craftsmanship guaranteed.',
    color: '#ec4899',
  },
  {
    number: 6,
    title: 'Final Walkthrough & Warranty',
    description: 'We do a detailed walkthrough with you, address any concerns, and provide warranty documentation for all work completed.',
    color: '#06b6d4',
  },
] as const;

// FAQ Data
export const FAQ_ITEMS = [
  {
    question: 'How long before I can use the tub?',
    answer: 'Your refinished surface is ready to use in just 24 hours. The coating continues to cure and harden over the next week, reaching maximum durability and hardness.',
  },
  {
    question: 'Is reglazing safe and low-odor?',
    answer: 'Yes! We use low-VOC, environmentally safe coatings. Our professional ventilation system ensures minimal odor during the process. The area is safe to use after 24 hours.',
  },
  {
    question: 'How long does refinishing last?',
    answer: 'With proper care, a professional refinishing job lasts 10-15 years or more. We back our work with a comprehensive 5-year warranty.',
  },
  {
    question: 'Do you repair chips or rust?',
    answer: 'Absolutely! Chip and crack repair is included in our refinishing process. We fill and smooth all damage before applying the new finish for a flawless result.',
  },
  {
    question: 'What does the warranty cover?',
    answer: 'Our 5-year warranty covers peeling, flaking, and adhesion issues. If anything goes wrong due to our workmanship, we fix it at no charge.',
  },
  {
    question: 'Will it look brand new after resurfacing?',
    answer: 'Yes! Our professional refinishing restores surfaces to factory-fresh condition. Most customers say their refinished tub looks better than new.',
  },
  {
    question: 'How can I get a quote or schedule service?',
    answer: 'Simply fill out our instant quote form or call us at (206) 786-9915. We respond instantly and can often schedule same-week appointments.',
  },
] as const;

export const REMODELING_FAQ_ITEMS = [
  {
    question: 'How long does a bathroom remodel take?',
    answer: 'A typical bathroom remodel takes 2-4 weeks depending on scope. Simple updates like new tile and vanity can be done in 1-2 weeks. Full gut renovations with layout changes may take 3-4 weeks.',
  },
  {
    question: 'How long does a kitchen remodel take?',
    answer: 'Kitchen remodels typically take 4-8 weeks. A cosmetic refresh (countertops, backsplash, paint) can be done in 2-3 weeks. Full renovations with new cabinets, plumbing, and electrical take 6-8 weeks.',
  },
  {
    question: 'Do you handle permits?',
    answer: 'Yes, we handle all necessary permits for your project. Building permits are required for most plumbing, electrical, and structural work in Seattle and surrounding areas.',
  },
  {
    question: 'Do you offer financing?',
    answer: 'We work with several financing partners to offer flexible payment options. Ask about our financing plans during your free consultation.',
  },
  {
    question: 'Are you licensed and insured?',
    answer: 'Yes, we are fully licensed, bonded, and insured in Washington State. We carry general liability insurance and workers compensation for your protection.',
  },
  {
    question: 'Can I stay in my home during remodeling?',
    answer: 'In most cases, yes. We work to minimize disruption and keep work areas contained. For kitchen remodels, we recommend setting up a temporary kitchen area.',
  },
  {
    question: 'What warranty do you provide?',
    answer: 'We provide a 5-year warranty on all workmanship. Manufacturer warranties on materials and fixtures are passed through to you. We stand behind every project.',
  },
] as const;

export const REMODELING_REVIEWS = [
  {
    name: 'Mark P.',
    location: 'Seattle, WA',
    rating: 5,
    text: 'Complete bathroom remodel done in under 2 weeks. New tile, vanity, shower — everything looks incredible. The team was professional and kept us informed throughout. Highly recommend for any remodeling project!',
    date: '1 week ago',
    service: 'Bathroom Remodeling',
  },
  {
    name: 'Karen W.',
    location: 'Bellevue, WA',
    rating: 5,
    text: 'They transformed our dated kitchen into a modern showpiece. New countertops, backsplash, and cabinet refresh. The attention to detail was outstanding and the price was very competitive.',
    date: '2 weeks ago',
    service: 'Kitchen Remodeling',
  },
  {
    name: 'Tom H.',
    location: 'Kirkland, WA',
    rating: 5,
    text: 'Had them install a walk-in shower to replace our old tub. The tile work is flawless and the glass enclosure looks amazing. Best home investment we\'ve made!',
    date: '3 weeks ago',
    service: 'Shower Installation',
  },
  {
    name: 'Rachel S.',
    location: 'Redmond, WA',
    rating: 5,
    text: 'New quartz countertops in our kitchen look absolutely stunning. Precise cuts, perfect seams, and they cleaned up everything after. Will definitely use them for our bathroom remodel next.',
    date: '1 month ago',
    service: 'Countertop Installation',
  },
  {
    name: 'Chris D.',
    location: 'Renton, WA',
    rating: 5,
    text: 'Tile installation in both bathrooms — floor and shower walls. Incredible craftsmanship, perfectly level, grout lines are immaculate. These guys know what they\'re doing.',
    date: '1 month ago',
    service: 'Tile Installation',
  },
] as const;

// Navigation
export const NAV_ITEMS = [
  { name: 'Services', href: '/services' },
  { name: 'Gallery', href: '/gallery' },
  { name: 'Process', href: '/process' },
  { name: 'Blog', href: '/blog' },
  { name: 'Locations', href: '/locations' },
  { name: 'Contact', href: '/contact' },
] as const;

// Blog Posts
export const BLOG_POSTS = [
  {
    id: 'bathtub-refinishing-vs-replacement-cost-seattle',
    slug: 'bathtub-refinishing-vs-replacement-cost-seattle',
    title: 'Bathtub Refinishing vs Replacement: Complete Cost Guide for Seattle Homeowners (2025)',
    excerpt: 'Discover the true costs of bathtub refinishing vs replacement in Seattle. Learn why 80% of homeowners choose refinishing and save $4,000+ on their bathroom renovation.',
    content: ``,
    author: 'Best Refinishing Team',
    date: '2025-08-15',
    readTime: '8 min read',
    category: 'Cost Guide',
    tags: ['bathtub refinishing cost', 'seattle bathroom renovation', 'tub replacement vs refinishing', 'save money bathroom'],
    image: '/images/optimized/IMG_5644.webp',
    featured: true,
  },
  {
    id: 'how-long-does-bathtub-refinishing-last',
    slug: 'how-long-does-bathtub-refinishing-last',
    title: 'How Long Does Bathtub Refinishing Last? Expert Guide to Durability & Care',
    excerpt: 'Professional bathtub refinishing lasts 10-15 years with proper care. Learn expert tips to maximize the lifespan of your refinished tub and what affects durability.',
    content: ``,
    author: 'Best Refinishing Team',
    date: '2025-07-22',
    readTime: '6 min read',
    category: 'Expert Guide',
    tags: ['bathtub refinishing durability', 'how long reglazing lasts', 'bathtub care tips', 'refinishing maintenance'],
    image: '/images/bathtub-4-after.webp',
    featured: true,
  },
] as const;

// Reviews/Testimonials
export const REVIEWS = [
  {
    name: 'Sarah M.',
    location: 'Seattle, WA',
    rating: 5,
    text: 'Absolutely amazing work! They transformed my old, stained bathtub into something that looks brand new. The team was professional, on time, and cleaned up everything after. Highly recommend!',
    date: '2 weeks ago',
    service: 'Bathtub Refinishing',
  },
  {
    name: 'Michael R.',
    location: 'Bellevue, WA',
    rating: 5,
    text: "Saved us thousands compared to replacing the tub. The finish looks incredible and they guaranteed their work for 5 years. Best money we've spent on home improvement.",
    date: '1 month ago',
    service: 'Bathtub & Tile Refinishing',
  },
  {
    name: 'Jennifer L.',
    location: 'Kirkland, WA',
    rating: 5,
    text: "Quick response, fair pricing, and excellent results. They fixed chips in my kitchen sink and countertop - you can't even tell there was ever any damage. Will use again!",
    date: '3 weeks ago',
    service: 'Chip & Crack Repair',
  },
  {
    name: 'David K.',
    location: 'Redmond, WA',
    rating: 5,
    text: 'Our shower looked terrible with all the grout stains and yellowed tiles. After their refinishing, it looks like we installed a completely new shower. Incredible transformation!',
    date: '1 month ago',
    service: 'Shower Refinishing',
  },
  {
    name: 'Lisa T.',
    location: 'Renton, WA',
    rating: 5,
    text: 'Professional from start to finish. They explained the whole process, gave us an honest quote, and delivered exactly what they promised. The bathtub looks beautiful!',
    date: '2 months ago',
    service: 'Bathtub Refinishing',
  },
] as const;
